// re_x64_tab0f.h - the x86-64 two byte opcode map, the one reached through 0F.
// Module: feature (C11).
// Owns: the 256 entry table for the 0F escape, including the 0F38 and 0F3A roots.
// Depends: re_x64_priv.h. A table, so it declares nothing and holds no state.
#include "features/disasm/re_x64_priv.h"

// Included by one translation unit only, but the gate wants the guard and a
// guard is free. Tables are file scope and hold no state.
#pragma once

// The 0F38 and 0F3A entries are escape roots: the real opcode is the next byte.
// The decoder reads that byte and treats every one of them as ModRM plus, for
// 0F3A, an imm8. Marking them XC_MODRM keeps that honest without a second table.
static const struct {
    uint8_t cls;
    const char *m;
} kOp0F[256] = {
    // 0x00 system and descriptor tables
    {XC_MODRM, "grp6"},
    {XC_MODRM, "grp7"},
    {XC_MODRM, "lar"},
    {XC_MODRM, "lsl"},
    {XC_BAD, NULL},
    {XC_NONE, "syscall"},
    {XC_NONE, "clts"},
    {XC_NONE, "sysret"},
    {XC_NONE, "invd"},
    {XC_NONE, "wbinvd"},
    {XC_BAD, NULL},
    {XC_NONE, "ud2"},
    {XC_BAD, NULL},
    {XC_MODRM, "prefetch"},
    {XC_NONE, "femms"},
    {XC_3DNOW, "3dnow"},
    // 0x10 the SSE moves, and the hint nops and prefetches
    {XC_MODRM, "movs"},
    {XC_MODRM, "movs"},
    {XC_MODRM, "movs"},
    {XC_MODRM, "movs"},
    {XC_MODRM, "grp18"},
    {XC_MODRM, "nop"},
    {XC_MODRM, "bndldx"},
    {XC_MODRM, "bndstx"},
    {XC_MODRM, "nop"},
    {XC_MODRM, "nop"},
    {XC_MODRM, "nop"},
    {XC_MODRM, "nop"},
    {XC_MODRM, "nop"},
    {XC_MODRM, "nop"},
    {XC_MODRM, "nop"},
    {XC_MODRM, "nop"},
    // 0x20 control registers, and the widening moves
    {XC_MODRM, "mov"},
    {XC_MODRM, "mov"},
    {XC_MODRM, "mov"},
    {XC_MODRM, "mov"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_MODRM, "movsxd"},
    {XC_MODRM, "movsxd"},
    {XC_MODRM, "cvt"},
    {XC_MODRM, "movnti"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    // 0x30 time and system counters, then the two more escape roots
    {XC_NONE, "wrmsr"},
    {XC_NONE, "rdtsc"},
    {XC_NONE, "rdmsr"},
    {XC_NONE, "rdpmc"},
    {XC_NONE, "sysenter"},
    {XC_NONE, "sysexit"},
    {XC_BAD, NULL},
    {XC_NONE, "getsec"},
    {XC_MODRM, "esc38"},
    {XC_BAD, NULL},
    {XC_MODRM, "esc3a"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    // 0x40 conditional moves
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    // 0x50 the single instruction, multiple data arithmetic block
    {XC_MODRM, "movmsk"},
    {XC_MODRM, "movs"},
    {XC_MODRM, "movs"},
    {XC_MODRM, "movs"},
    {XC_MODRM, "andps"},
    {XC_MODRM, "andnps"},
    {XC_MODRM, "orps"},
    {XC_MODRM, "xorps"},
    {XC_MODRM, "add"},
    {XC_MODRM, "mul"},
    {XC_MODRM, "cvt"},
    {XC_MODRM, "cvt"},
    {XC_MODRM, "sub"},
    {XC_MODRM, "min"},
    {XC_MODRM, "div"},
    {XC_MODRM, "max"},
    // 0x60 integer SIMD, none of which carries an immediate
    {XC_MODRM, "punpck"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "packus"},
    {XC_MODRM, "pcmpgt"},
    {XC_MODRM, "pcmpgt"},
    {XC_MODRM, "pcmpgt"},
    {XC_MODRM, "packus"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "packus"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "movd"},
    {XC_MODRM, "movdqa"},
    // 0x70 the shift groups with their imm8, the compares, and emms
    {XC_MODRM_IB, "pshuf"},
    {XC_MODRM_IB, "grp12"},
    {XC_MODRM_IB, "grp13"},
    {XC_MODRM_IB, "grp14"},
    {XC_MODRM, "pcmpeq"},
    {XC_MODRM, "pcmpeq"},
    {XC_MODRM, "pcmpeq"},
    {XC_NONE, "emms"},
    // 0x78 VMM and the horizontal SIMD ops, then the long conditional jumps
    {XC_MODRM, "vmread"},
    {XC_MODRM, "vmwrite"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_MODRM, "hadd"},
    {XC_MODRM, "hadd"},
    {XC_MODRM, "movd"},
    {XC_MODRM, "movq"},
    {XC_REL32, "jo"},
    {XC_REL32, "jno"},
    {XC_REL32, "jb"},
    {XC_REL32, "jae"},
    {XC_REL32, "je"},
    {XC_REL32, "jne"},
    {XC_REL32, "jbe"},
    {XC_REL32, "ja"},
    {XC_REL32, "js"},
    {XC_REL32, "jns"},
    {XC_REL32, "jp"},
    {XC_REL32, "jnp"},
    {XC_REL32, "jl"},
    {XC_REL32, "jge"},
    {XC_REL32, "jle"},
    {XC_REL32, "jg"},
    // 0x90 set on condition, system segments, and the control transfers
    {XC_MODRM, "seto"},
    {XC_MODRM, "setno"},
    {XC_MODRM, "setb"},
    {XC_MODRM, "setae"},
    {XC_MODRM, "sete"},
    {XC_MODRM, "setne"},
    {XC_MODRM, "setbe"},
    {XC_MODRM, "seta"},
    {XC_MODRM, "sets"},
    {XC_MODRM, "setns"},
    {XC_MODRM, "setp"},
    {XC_MODRM, "setnp"},
    {XC_MODRM, "setl"},
    {XC_MODRM, "setge"},
    {XC_MODRM, "setle"},
    {XC_MODRM, "setg"},
    {XC_NONE, "push"},
    {XC_NONE, "pop"},
    {XC_NONE, "cpuid"},
    {XC_MODRM, "bt"},
    {XC_MODRM_IB, "shld"},
    {XC_MODRM, "shld"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    // 0xA8 the other system segment, bit instructions, and the group 8 shifts
    {XC_NONE, "push"},
    {XC_NONE, "pop"},
    {XC_NONE, "rsm"},
    {XC_MODRM, "bts"},
    {XC_MODRM_IB, "shrd"},
    {XC_MODRM, "shrd"},
    {XC_MODRM, "grp15"},
    {XC_MODRM, "imul"},
    {XC_MODRM, "cmpxchg"},
    {XC_MODRM, "cmpxchg"},
    {XC_MODRM, "lss"},
    {XC_MODRM, "btr"},
    {XC_MODRM, "lfs"},
    {XC_MODRM, "lgs"},
    {XC_MODRM, "movzx"},
    {XC_MODRM, "movzx"},
    {XC_MODRM, "popcnt"},
    {XC_MODRM, "ud1"},
    {XC_MODRM_IB, "grp8"},
    {XC_MODRM, "btc"},
    {XC_MODRM, "bsf"},
    {XC_MODRM, "bsr"},
    {XC_MODRM, "movsx"},
    {XC_MODRM, "movsx"},
    // 0xC0 the exchange and packed compare forms, then the byte swaps
    {XC_MODRM, "xadd"},
    {XC_MODRM, "xadd"},
    {XC_MODRM_IB, "cmpps"},
    {XC_MODRM, "movnti"},
    {XC_MODRM_IB, "pinsrw"},
    {XC_MODRM_IB, "pextrw"},
    {XC_MODRM_IB, "shufps"},
    {XC_MODRM, "grp9"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_MODRM_IB, "padd"},
    {XC_MODRM_IB, "padd"},
    {XC_MODRM_IB, "padd"},
    {XC_MODRM_IB, "padd"},
    {XC_MODRM_IB, "padd"},
    {XC_MODRM_IB, "padd"},
    {XC_MODRM_IB, "padd"},
    {XC_MODRM, "pmovmskb"},
    // 0xD8 onward, every remaining packed op carries an imm8 selector
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
    {XC_MODRM_IB, "p"},
};
