// re_x64_tab.h - the x86-64 one byte opcode map: class plus base mnemonic.
// Module: feature (C11).
// Owns: the 256 entry primary opcode table. The 0F map lives in re_x64_tab0f.h.
// Depends: re_x64_priv.h. A table, so it declares nothing and holds no state.
#include "features/disasm/re_x64_priv.h"

// Included by one translation unit only, but the gate wants the guard and a
// guard is free. Tables are file scope and hold no state.
#pragma once

// Group opcodes carry a placeholder: the reg field in the ModRM picks the real
// mnemonic, and that is only known once the ModRM has been read.
static const struct {
    uint8_t cls;
    const char *m;
} kOp1[256] = {
    // 0x00 arithmetic and logic, byte and word/dword/qword forms
    {XC_MODRM_IB, "add"},
    {XC_MODRM, "add"},
    {XC_MODRM_IB, "add"},
    {XC_MODRM, "add"},
    {XC_IB, "add"},
    {XC_IZ, "add"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_MODRM_IB, "or"},
    {XC_MODRM, "or"},
    {XC_MODRM_IB, "or"},
    {XC_MODRM, "or"},
    {XC_IB, "or"},
    {XC_IZ, "or"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    // 0x10 carry and borrow
    {XC_MODRM_IB, "adc"},
    {XC_MODRM, "adc"},
    {XC_MODRM_IB, "adc"},
    {XC_MODRM, "adc"},
    {XC_IB, "adc"},
    {XC_IZ, "adc"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_MODRM_IB, "sbb"},
    {XC_MODRM, "sbb"},
    {XC_MODRM_IB, "sbb"},
    {XC_MODRM, "sbb"},
    {XC_IB, "sbb"},
    {XC_IZ, "sbb"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    // 0x20 and, subtract, and compare
    {XC_MODRM_IB, "and"},
    {XC_MODRM, "and"},
    {XC_MODRM_IB, "and"},
    {XC_MODRM, "and"},
    {XC_IB, "and"},
    {XC_IZ, "and"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_MODRM_IB, "sub"},
    {XC_MODRM, "sub"},
    {XC_MODRM_IB, "sub"},
    {XC_MODRM, "sub"},
    {XC_IB, "sub"},
    {XC_IZ, "sub"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_MODRM_IB, "xor"},
    {XC_MODRM, "xor"},
    {XC_MODRM_IB, "xor"},
    {XC_MODRM, "xor"},
    {XC_IB, "xor"},
    {XC_IZ, "xor"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_MODRM_IB, "cmp"},
    {XC_MODRM, "cmp"},
    {XC_MODRM_IB, "cmp"},
    {XC_MODRM, "cmp"},
    {XC_IB, "cmp"},
    {XC_IZ, "cmp"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    // 0x40 REX, consumed as a prefix, never an opcode
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    // 0x50 push and pop
    {XC_NONE, "push"},
    {XC_NONE, "push"},
    {XC_NONE, "push"},
    {XC_NONE, "push"},
    {XC_NONE, "push"},
    {XC_NONE, "push"},
    {XC_NONE, "push"},
    {XC_NONE, "push"},
    {XC_NONE, "pop"},
    {XC_NONE, "pop"},
    {XC_NONE, "pop"},
    {XC_NONE, "pop"},
    {XC_NONE, "pop"},
    {XC_NONE, "pop"},
    {XC_NONE, "pop"},
    {XC_NONE, "pop"},
    // 0x60 invalid, the escapes, and the prefix bytes
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_MODRM, "movsxd"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_IZ, "push"},
    {XC_MODRM_IZ, "imul"},
    {XC_MODRM_IB, "imul"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    // 0x70 short conditional jumps
    {XC_REL8, "jo"},
    {XC_REL8, "jno"},
    {XC_REL8, "jb"},
    {XC_REL8, "jae"},
    {XC_REL8, "je"},
    {XC_REL8, "jne"},
    {XC_REL8, "jbe"},
    {XC_REL8, "ja"},
    {XC_REL8, "js"},
    {XC_REL8, "jns"},
    {XC_REL8, "jp"},
    {XC_REL8, "jnp"},
    {XC_REL8, "jl"},
    {XC_REL8, "jge"},
    {XC_REL8, "jle"},
    {XC_REL8, "jg"},
    // 0x80 group 1, test, xchg, mov, lea, and the pop group
    {XC_MODRM_IB, "grp1"},
    {XC_MODRM_IZ, "grp1"},
    {XC_BAD, NULL},
    {XC_MODRM_IZB, "grp1"},
    {XC_MODRM, "test"},
    {XC_MODRM, "test"},
    {XC_MODRM, "xchg"},
    {XC_MODRM, "xchg"},
    {XC_MODRM, "mov"},
    {XC_MODRM, "mov"},
    {XC_MODRM, "mov"},
    {XC_MODRM, "mov"},
    {XC_MODRM, "mov"},
    {XC_MODRM, "lea"},
    {XC_MODRM, "mov"},
    {XC_MODRM, "pop"},
    // 0x90 nop and the accumulator shuffles
    {XC_NONE, "nop"},
    {XC_NONE, "xchg"},
    {XC_NONE, "xchg"},
    {XC_NONE, "xchg"},
    {XC_NONE, "xchg"},
    {XC_NONE, "xchg"},
    {XC_NONE, "xchg"},
    {XC_NONE, "xchg"},
    {XC_NONE, "cbw"},
    {XC_NONE, "cwd"},
    {XC_BAD, NULL},
    {XC_NONE, "wait"},
    {XC_NONE, "pushf"},
    {XC_NONE, "popf"},
    {XC_NONE, "sahf"},
    {XC_NONE, "lahf"},
    // 0xA0 absolute moves and the string primitives
    {XC_PTR, "mov"},
    {XC_PTR, "mov"},
    {XC_PTR, "mov"},
    {XC_PTR, "mov"},
    {XC_NONE, "movsb"},
    {XC_NONE, "movsd"},
    {XC_NONE, "cmpsb"},
    {XC_NONE, "cmpsd"},
    {XC_IB, "test"},
    {XC_IZ, "test"},
    {XC_NONE, "stosb"},
    {XC_NONE, "stosd"},
    {XC_NONE, "lodsb"},
    {XC_NONE, "lodsd"},
    {XC_NONE, "scasb"},
    {XC_NONE, "scasd"},
    // 0xB0 mov into a byte register, then mov into any register
    {XC_IB, "mov"},
    {XC_IB, "mov"},
    {XC_IB, "mov"},
    {XC_IB, "mov"},
    {XC_IB, "mov"},
    {XC_IB, "mov"},
    {XC_IB, "mov"},
    {XC_IB, "mov"},
    {XC_IV, "mov"},
    {XC_IV, "mov"},
    {XC_IV, "mov"},
    {XC_IV, "mov"},
    {XC_IV, "mov"},
    {XC_IV, "mov"},
    {XC_IV, "mov"},
    {XC_IV, "mov"},
    // 0xC0 shift group, returns, and the move group
    {XC_MODRM_IB, "grp2"},
    {XC_MODRM_IB, "grp2"},
    {XC_IW, "ret"},
    {XC_NONE, "ret"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_MODRM_IB, "grp11"},
    {XC_MODRM_IZ, "grp11"},
    {XC_IW_IB, "enter"},
    {XC_NONE, "leave"},
    {XC_IW, "retf"},
    {XC_NONE, "retf"},
    {XC_NONE, "int3"},
    {XC_IB, "int"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    // 0xD0 shift group, the x87 escape, and the reserved slots
    {XC_MODRM, "grp2"},
    {XC_MODRM, "grp2"},
    {XC_MODRM, "grp2"},
    {XC_MODRM, "grp2"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_NONE, "xlat"},
    {XC_MODRM, "x87"},
    {XC_MODRM, "x87"},
    {XC_MODRM, "x87"},
    {XC_MODRM, "x87"},
    {XC_MODRM, "x87"},
    {XC_MODRM, "x87"},
    {XC_MODRM, "x87"},
    {XC_MODRM, "x87"},
    // 0xE0 loops, port io, and the near control transfers
    {XC_REL8, "loopne"},
    {XC_REL8, "loope"},
    {XC_REL8, "loop"},
    {XC_REL8, "jcxz"},
    {XC_IB, "in"},
    {XC_IB, "in"},
    {XC_IB, "out"},
    {XC_IB, "out"},
    {XC_REL32, "call"},
    {XC_REL32, "jmp"},
    {XC_BAD, NULL},
    {XC_REL8, "jmp"},
    {XC_NONE, "in"},
    {XC_NONE, "in"},
    {XC_NONE, "out"},
    {XC_NONE, "out"},
    // 0xF0 the prefix bytes, then the remaining groups
    {XC_BAD, NULL},
    {XC_NONE, "int1"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_NONE, "hlt"},
    {XC_NONE, "cmc"},
    {XC_MODRM_F6, "grp3"},
    {XC_MODRM_F7, "grp3"},
    {XC_NONE, "clc"},
    {XC_NONE, "stc"},
    {XC_NONE, "cli"},
    {XC_NONE, "sti"},
    {XC_NONE, "cld"},
    {XC_NONE, "std"},
    {XC_MODRM, "grp4"},
    {XC_MODRM, "grp5"},
};
