// re_x64_tab0f.h - the x86-64 two byte opcode map, the one reached through 0F.
// Module: feature (C11).
// Owns: the 256 entry table for the 0F escape, including the 0F38 and 0F3A roots.
// Depends: re_x64_priv.h. A table, so it declares nothing and holds no state.
#include "features/disasm/re_x64_priv.h"

// Included by one translation unit only, but the gate wants the guard and a
// guard is free. Tables are file scope and hold no state.
#pragma once

// The 0F38 and 0F3A entries are escape roots: the real opcode is the next byte.
// The decoder reads that byte and treats every one of them as ModRM plus, for
// 0F3A, an imm8. Marking them XC_MODRM keeps that honest without a second table.
static const struct {
    uint8_t cls;
    const char *m;
} kOp0F[256] = {
    // 0x00 system and descriptor tables
    {XC_MODRM, "grp6"},
    {XC_MODRM, "grp7"},
    {XC_MODRM, "lar"},
    {XC_MODRM, "lsl"},
    {XC_BAD, NULL},
    {XC_NONE, "syscall"},
    {XC_NONE, "clts"},
    {XC_NONE, "sysret"},
    {XC_NONE, "invd"},
    {XC_NONE, "wbinvd"},
    {XC_BAD, NULL},
    {XC_NONE, "ud2"},
    {XC_BAD, NULL},
    {XC_MODRM, "grp0d"},
    {XC_NONE, "femms"},
    {XC_3DNOW, "3dnow"},
    // 0x10 the SSE moves, the prefetch group, and the hint nops
    {XC_MODRM, "movs"},
    {XC_MODRM, "movs"},
    {XC_MODRM, "movs"},
    {XC_MODRM, "movs"},
    {XC_MODRM, "unpcklps"},
    {XC_MODRM, "unpckhps"},
    {XC_MODRM, "movhps"},
    {XC_MODRM, "movhps"},
    {XC_MODRM, "grp18"},
    {XC_MODRM, "nop"},
    // 0x1A and 0x1B are the bounds moves, whose name the prefix decides, and 0x1C
    // is the cache line demote. Everything else in here is a multi byte nop.
    {XC_MODRM, NULL},
    {XC_MODRM, NULL},
    {XC_MODRM, "grp1c"},
    {XC_MODRM, "nop"},
    {XC_MODRM, "nop"},
    {XC_MODRM, "nop"},
    // 0x20 control registers, and the widening moves
    {XC_MODRM_NOMEM, "mov"},
    {XC_MODRM_NOMEM, "mov"},
    {XC_MODRM_NOMEM, "mov"},
    {XC_MODRM_NOMEM, "mov"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_MODRM, "movaps"},
    {XC_MODRM, "movaps"},
    {XC_MODRM, "cvt"},
    {XC_MODRM, "movnt"},
    {XC_MODRM, "cvt"},
    {XC_MODRM, "cvt"},
    {XC_MODRM, "ucomis"},
    {XC_MODRM, "comis"},
    // 0x30 time and system counters, then the two more escape roots
    {XC_NONE, "wrmsr"},
    {XC_NONE, "rdtsc"},
    {XC_NONE, "rdmsr"},
    {XC_NONE, "rdpmc"},
    {XC_NONE, "sysenter"},
    {XC_NONE, "sysexit"},
    {XC_BAD, NULL},
    {XC_NONE, "getsec"},
    {XC_MODRM, "esc38"},
    {XC_BAD, NULL},
    {XC_MODRM, "esc3a"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    // 0x40 conditional moves
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    {XC_MODRM, "cmov"},
    // 0x50 the single instruction, multiple data arithmetic block
    {XC_MODRM, "movmsk"},
    {XC_MODRM, "movs"},
    {XC_MODRM, "movs"},
    {XC_MODRM, "movs"},
    {XC_MODRM, "andps"},
    {XC_MODRM, "andnps"},
    {XC_MODRM, "orps"},
    {XC_MODRM, "xorps"},
    {XC_MODRM, "add"},
    {XC_MODRM, "mul"},
    {XC_MODRM, "cvt"},
    {XC_MODRM, "cvt"},
    {XC_MODRM, "sub"},
    {XC_MODRM, "min"},
    {XC_MODRM, "div"},
    {XC_MODRM, "max"},
    // 0x60 integer SIMD, none of which carries an immediate
    {XC_MODRM, "punpck"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "packus"},
    {XC_MODRM, "pcmpgt"},
    {XC_MODRM, "pcmpgt"},
    {XC_MODRM, "pcmpgt"},
    {XC_MODRM, "packus"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "packus"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "punpck"},
    {XC_MODRM, "movd"},
    {XC_MODRM, "movdqa"},
    // 0x70 the shift groups with their imm8, the compares, and emms
    {XC_MODRM_IB, "pshuf"},
    {XC_MODRM_IB, "grp12"},
    {XC_MODRM_IB, "grp13"},
    {XC_MODRM_IB, "grp14"},
    {XC_MODRM, "pcmpeq"},
    {XC_MODRM, "pcmpeq"},
    {XC_MODRM, "pcmpeq"},
    {XC_NONE, "emms"},
    // 0x78 VMM and the horizontal SIMD ops, then the long conditional jumps
    {XC_MODRM, "vmread"},
    {XC_MODRM, "vmwrite"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    {XC_MODRM, "hadd"},
    {XC_MODRM, "hadd"},
    {XC_MODRM, "movd"},
    {XC_MODRM, "movq"},
    {XC_REL32, "jo"},
    {XC_REL32, "jno"},
    {XC_REL32, "jb"},
    {XC_REL32, "jae"},
    {XC_REL32, "je"},
    {XC_REL32, "jne"},
    {XC_REL32, "jbe"},
    {XC_REL32, "ja"},
    {XC_REL32, "js"},
    {XC_REL32, "jns"},
    {XC_REL32, "jp"},
    {XC_REL32, "jnp"},
    {XC_REL32, "jl"},
    {XC_REL32, "jge"},
    {XC_REL32, "jle"},
    {XC_REL32, "jg"},
    // 0x90 set on condition, system segments, and the control transfers
    {XC_MODRM, "seto"},
    {XC_MODRM, "setno"},
    {XC_MODRM, "setb"},
    {XC_MODRM, "setae"},
    {XC_MODRM, "sete"},
    {XC_MODRM, "setne"},
    {XC_MODRM, "setbe"},
    {XC_MODRM, "seta"},
    {XC_MODRM, "sets"},
    {XC_MODRM, "setns"},
    {XC_MODRM, "setp"},
    {XC_MODRM, "setnp"},
    {XC_MODRM, "setl"},
    {XC_MODRM, "setge"},
    {XC_MODRM, "setle"},
    {XC_MODRM, "setg"},
    {XC_NONE, "push"},
    {XC_NONE, "pop"},
    {XC_NONE, "cpuid"},
    {XC_MODRM, "bt"},
    {XC_MODRM_IB, "shld"},
    {XC_MODRM, "shld"},
    {XC_BAD, NULL},
    {XC_BAD, NULL},
    // 0xA8 the other system segment, bit instructions, and the group 8 shifts
    {XC_NONE, "push"},
    {XC_NONE, "pop"},
    {XC_NONE, "rsm"},
    {XC_MODRM, "bts"},
    {XC_MODRM_IB, "shrd"},
    {XC_MODRM, "shrd"},
    {XC_MODRM, "grp15"},
    {XC_MODRM, "imul"},
    {XC_MODRM, "cmpxchg"},
    {XC_MODRM, "cmpxchg"},
    {XC_MODRM, "lss"},
    {XC_MODRM, "btr"},
    {XC_MODRM, "lfs"},
    {XC_MODRM, "lgs"},
    {XC_MODRM, "movzx"},
    {XC_MODRM, "movzx"},
    {XC_MODRM, "popcnt"},
    {XC_MODRM, "ud1"},
    {XC_MODRM_IB, "grp8"},
    {XC_MODRM, "btc"},
    {XC_MODRM, "bsf"},
    {XC_MODRM, "bsr"},
    {XC_MODRM, "movsx"},
    {XC_MODRM, "movsx"},
    // 0xC0 the exchange and packed compare forms, then the byte swaps
    {XC_MODRM, "xadd"},
    {XC_MODRM, "xadd"},
    {XC_MODRM_IB, "cmpps"},
    {XC_MODRM, "movnti"},
    {XC_MODRM_IB, "pinsrw"},
    {XC_MODRM_IB, "pextrw"},
    {XC_MODRM_IB, "shufps"},
    {XC_MODRM, "grp9"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_NONE, "bswap"},
    {XC_MODRM, "addsub"},
    {XC_MODRM, "psrlw"},
    {XC_MODRM, "psrld"},
    {XC_MODRM, "psrlq"},
    {XC_MODRM, "paddq"},
    {XC_MODRM, "pmullw"},
    {XC_MODRM, "movq"},
    {XC_MODRM, "pmovmskb"},
    // 0xD8 to 0xFF: the packed integer block. Only 0F F0 carries an
    // immediate, and only when 0x66 selects pshufd; F2 the same opcode is
    // lddqu, which carries none. That one is decided by the prefix in the
    // decoder, because a class table has room for one class per opcode.
    {XC_MODRM, "psubusb"},
    {XC_MODRM, "psubusw"},
    {XC_MODRM, "pminub"},
    {XC_MODRM, "pand"},
    {XC_MODRM, "paddusb"},
    {XC_MODRM, "paddusw"},
    {XC_MODRM, "pmaxub"},
    {XC_MODRM, "pandn"},
    {XC_MODRM, "pavgb"},
    {XC_MODRM, "psraw"},
    {XC_MODRM, "psrad"},
    {XC_MODRM, "pavgw"},
    {XC_MODRM, "pmulhuw"},
    {XC_MODRM, "pmulhw"},
    {XC_MODRM, "cvt"},
    {XC_MODRM, "movnt"},
    {XC_MODRM, "psubsb"},
    {XC_MODRM, "psubsw"},
    {XC_MODRM, "pminsw"},
    {XC_MODRM, "por"},
    {XC_MODRM, "paddsb"},
    {XC_MODRM, "paddsw"},
    {XC_MODRM, "pmaxsw"},
    {XC_MODRM, "pxor"},
    {XC_MODRM_IB, "pshufd"},
    {XC_MODRM, "psllw"},
    {XC_MODRM, "pslld"},
    {XC_MODRM, "psllq"},
    {XC_MODRM, "pmuludq"},
    {XC_MODRM, "pmaddwd"},
    {XC_MODRM, "psadbw"},
    {XC_MODRM, NULL},
    {XC_MODRM, "psubb"},
    {XC_MODRM, "psubw"},
    {XC_MODRM, "psubd"},
    {XC_MODRM, "psubq"},
    {XC_MODRM, "paddb"},
    {XC_MODRM, "paddw"},
    {XC_MODRM, "paddd"},
    {XC_MODRM, "ud0"},
};
